name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install System Dependencies
      run: |
        sudo add-apt-repository ppa:criu/ppa
        sudo apt-get update
        sudo apt-get install -qqy protobuf-compiler libprotobuf-dev criu

    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true

    - name: Run tests
      run: make test

    - name: Run end-to-end tests
      run: sudo -E make test-e2e