name: CRIU Coordinator CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install System Dependencies
      run: |
        sudo add-apt-repository -y ppa:criu/ppa
        sudo apt-get update
        sudo apt-get install -qqy protobuf-compiler libprotobuf-dev criu podman \
        make git gcc build-essential pkgconf libtool \
        libsystemd-dev libprotobuf-c-dev libcap-dev libseccomp-dev libyajl-dev \
        go-md2man autoconf python3 automake

    - name:  Check CRIU version
      run: criu --version

    - name: Build and Install crun with CRIU support
      run: |
        git clone https://github.com/containers/crun
        cd crun
        ./autogen.sh
        ./configure
        make
        sudo make install

    - name: Replace crun with the compiled version
      run: |
        sudo rm -f /usr/bin/crun
        sudo ln -s /usr/local/bin/crun /usr/bin/crun
        
    - name: Run tests
      run: make test

    - name: Run end-to-end tests
      run: sudo -E make test-e2e